/* Error codes*/
#define MODBUS_BASEERR (1<<29)
#define MODBUS_EINVALIDRATE MODBUS_BASEERR+1
#define MODBUS_EMAXBUF MODBUS_BASEERR+2
#define MODBUS_ECHECKSUM MODBUS_BASEERR+3
#define MODBUS_EINVALIDREPLY MODBUS_BASEERR+4
#define MODBUS_EREFUSED MODBUS_BASEERR+5
#define MODBUS_EBUSY MODBUS_BASEERR+6
#define MODBUS_ENOTINIT MODBUS_BASEERR+7
#define MODBUS_EOVERFLOW MODBUS_BASEERR+8
#define MODBUS_ENOREPLY MODBUS_BASEERR+9
#define MODBUS_EINVALIDPARAM MODBUS_BASEERR+10
#define MODBUS_LASTERR MODBUS_BASEERR+10

